# Simulation

In this lesson, we will work through several examples of using random numbers to simulate real-world scenarios.

In [4]:
%matplotlib inline
import numpy as np
import pandas as pd



np.random.seed(1349)

### How will we utilize Python to obtain probabilities?

We will utilize Monte Carlo simulations.

A Monte Carlo simulation is a means to recreate potential events and empirically take the results of simiulated trials to obtain a reasonably precise estimate of a desired probability.

What does this mean for us here?

In [2]:
# Let's take a hypothetical base probability. 
# What is the probability of rolling a one (1) on a single, standard, fair six-sided die?


In [3]:
# Potential outcomes of a die roll:


In [4]:
# options that equal 1: just 1, literally one

In [5]:
# Now how would we do this with a simulation?


In [6]:
# We will do it utilizing a large number of trials, that we calculate.

In [7]:
# Allow us to examine the same problem: Probability of rolling a 1 on a fair six-sided die.

In [8]:
# First, we will set a value for the number of trials that we want to conduct.
# We have the power of computation at our finger tips, so let's shoot for something like one million.



In [9]:
# We have one die roll for each trial, which is our event, that we call a single simulation


In [10]:
# We will do a single simulation one million times, with each simulation being a die roll.

In [11]:
# let's make our simulations!

## Generating Random Numbers with Numpy

The `numpy.random` module provides a number of functions for generating random numbers.

- `np.random.choice`: selects random options from a list
- `np.random.uniform`: generates numbers between a given lower and upper bound
- `np.random.random`: generates numbers between 0 and 1
- `np.random.randn`: generates numbers from the standard normal distribution
- `np.random.normal`: generates numbers from a normal distribution with a specified mean and standard deviation

## Example Problems

### Carnival Dice Rolls

> You are at a carnival and come across a person in a booth offering you a game
> of "chance" (as people in booths at carnivals tend to do).

> You pay 5 dollars and roll 3 dice. If the sum of the dice rolls is greater
> than 12, you get 15 dollars. If it's less than or equal to 12, you get
> nothing.

> Assuming the dice are fair, should you play this game? How would this change
> if the winning condition was a sum greater than *or equal to* 12?

To simulate this problem, we'll write the python code to simulate the scenario described above, then repeat it a large amount of times.

One way we can keep track of all the simulations is to use a 2-dimensional matrix. We can create a matrix where each row represents one "trial". Each row will have 3 columns, representing the 3 dice rolls.

In [12]:
n_trials = 
n_dice = 

rolls = 

SyntaxError: invalid syntax (<ipython-input-12-25b731508e77>, line 1)

Here we used the `choice` function to randomly select an element out of the list of the number 1-6, effectively simulating a dice roll. The second argument supplied to `choice` is the total number of dice to roll. Once we have generated all the dice rolls, we use the `.reshape` method to create our matrix with 3 columns and 10,000 rows.

Now that we have all of the simulated dice rolls, we want to get the sum of the dice rolls for each trial. To do this, we can use the `.sum` function and specify that we want the sum of every row (as opposed to the sum of all the numbers, or the sum by column) with the `axis` key word argument.

In [ ]:
sums_by_trial = 
sums_by_trial

Let's pause here for a minute and visualize the data we have:

In [ ]:
viz.simulation_example1(sums_by_trial)

The area shaded in lightblue represents our chance of winning, that is, the number of times that the sum of 3 dice rolls is greater than 12.

We can now convert each value in our array to a boolean value indicating whether or not we won:

To calculate an overall win rate, we can treat each win as a `1` and each loss as `0`, then take the average of the array:

Now that we know our win rate, we can calculate the expected profit:

In [ ]:
expected_winnings = 
cost = 
expected_profit = 
expected_profit

So we would expect, based on our simulations, on average, to lose a little over a dollar everytime we play this game.

To answer the last part of the question, we can recalculate our win rate based on the sums being greater than or equal to 12:

In [ ]:
wins = 
win_rate = 
expected_winnings = 
cost = 
expected_profit = 
expected_profit

If our win condition changes to the sum being greater than or equal to 12, then, based on our simulations, on average, we expect to win about 58 cents.

## Mini Exercise:

What is the probability of rolling "snake eyes" on a roll of two (fair) dice?

In [ ]:
n_sims = n_rows = 10 ** 5
n_dice = n_cols = 2
dice_roll = [1,2,3,4,5,6]
rolls = np.random.choice(dice_roll, n_sims * n_cols).reshape(n_rows, n_cols)
rolls

In [ ]:
(rolls.sum(axis = 1) == 2).mean()

### No Rest or Relaxation

> There's a 30% chance my son takes a nap on any given weekend day. What is the chance that he takes a nap at least one day this weekend? What is the probability that he doesn't nap at all?

Let's first do a little bit of setup:

In [ ]:
p_nap = 
ndays = n_cols = 
n_simulated_weekends = 

To simulate the results from many weekends, we'll create a 2 x 10,000 matrix, with 2 being the number of days in a weekend and 10,000 being the number of simulations we want to run.

To determine whether or not a nap is taken on a given day, we'll generate a random number between 0 and 1, and say that it is a nap if it is less than our probability of taking a nap.

Now that we have each day as either true or false, we can take the sum of each row to find the total number of naps for the weekend. When we sum an array of boolean values, numpy will treat `True` as 1 and `False` as 0.

Now we have the results of our simulation, an array where each number in the array represents how many naps were taken in a two day weekend.

In [ ]:
viz.simulation_example2(naps)

We can use this to answer our original questions, what is the probability that at least one nap is taken?

What is the probability no naps are taken?

## Mini Exercise:

There are ten options in a blind-box style collectable, but you are only likely to get the one you want the most at a probability of one out of every twenty boxes because its a little rarer.

What is the probability of getting your desired collectable if you buy three blindbox toys?

In [ ]:
p_want = 1/20
n_trials = n_cols = 10 ** 5
n_sims = n_cols = 3

total_purchases = np.random.random((n_rows,n_cols))
total_purchases

In [ ]:
((total_purchases < p_want).sum(axis = 1) >= 1).mean()

### One With Dataframes

Let's take a look at one more problem:

> What is the probability of getting at least one 3 in 3 dice rolls?

To simulate this, we'll use a similar strategy to how we modeled the dice rolls in the previous example, but this time, we'll store the results in a pandas dataframe so that we can apply a lambda function that will check to see if one of the rolls was a 3.

In [ ]:
n_simulations = nrows = 
n_dice_rolled = ncols = 

rolls = 

Let's break down what's going on here:

1. First we assign values for the number of rows and columns we are going to use
1. Next we create the `rolls` variable that holds a 3 x 10,000 matrix where each element is a randomly chosen number from 1 to 6
1. Lastly we create a dataframe from the rolls
    1. `pd.DataFrame(rolls)` converts our 2d numpy matrix to a pandas DataFrame
    1. `.apply(...` applies a function to each **row** in our dataframe, because we specified `axis=1`, the function will be called with each row as it's argument. The body of the function checks to see if the value `3` is in the values of the row, and will return either `True` or `False`
    1. `.mean()` takes our resulting series of boolean values, and treats `True` as 1 and `False` as 0, to give us the average rate of `True`s, in this case, the simulated probability of getting a 3 in 3 dice rolls.

## Mini Exercise:

Recreate the blindbox problem utilizing the above strategy!


In [ ]:
n_rows = 100000
n_cols = 3
outcomes = [1,2,3,4,5,6,7,8,9,10]
prob_win = 0.05
prob_others = (1-0.05)/9

In [ ]:
p = [prob_win, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others]


In [ ]:
data = np.random.choice(outcomes, n_rows*n_cols, p = [prob_win, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others]).reshape(n_rows, n_cols)
data

In [ ]:
pd.DataFrame(data).apply(lambda x: 1 in x.values, axis =1).mean()

## Exercises

Within your `codeup-data-science directory`, create a directory named `statistics-exercises`. This will be where you do your work for this module. Create a repository on GitHub with the same name, and link your local repository to GitHub.

Do your work for this exercise in either a python file named `simulation.py` or a jupyter notebook named `simulation.ipynb`.

1. How likely is it that you roll doubles when rolling two dice?

1. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

1. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

1. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

1. Compare Heights

    - Men have an average height of 178 cm and standard deviation of 8cm.
    - Women have a mean of 170, sd = 6cm.
    - If a man and woman are chosen at random, P(woman taller than man)?

1. When installing anaconda on a student's computer, there's a 1 in 250 chance
   that the download is corrupted and the installation fails. What are the odds
   that after having 50 students download anaconda, no one has an installation
   issue?  100 students?

    What is the probability that we observe an installation issue within the first
    150 students that download anaconda?

    How likely is it that 450 students all download anaconda without an issue?

1. There's a 70% chance on any given day that there will be at least one food
   truck at Travis Park. However, you haven't seen a food truck there in 3 days.
   How unlikely is this?

    How likely is it that a food truck will show up sometime this week?

1. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

#### Bonus Exercises
- [Mage Duel](https://gist.github.com/ryanorsinger/2996446f02c1bf30fcb3f8fdb88bd51d)
- [Chuck a Luck](https://gist.github.com/ryanorsinger/eac1d7b7e978f90b8390bdc056312123)

Question 1: How likely is it that you roll doubles when rolling two dice?



In [2]:
outcomes = [1,2,3,4,5,6]
n_rows = 10 ** 6
n_cols = 2

In [5]:
rolls = np.random.choice(outcomes, size=(n_rows, n_cols))
rolls

array([[3, 2],
       [5, 3],
       [4, 4],
       ...,
       [3, 4],
       [6, 1],
       [2, 1]])

In [6]:
doubles = [len(np.unique(rolls[n])) for n in range(0, n_rows-1) if len(np.unique(rolls[n])) ==1]
chance = len(doubles) / len(rolls)
chance

0.166136

Question 2: If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?



In [19]:
n_trials = n_rows = 10 ** 6
n_sims = n_cols = 8
heads = 1 
tails = 0
flips = np.random.choice([heads,tails], size=(n_rows, n_cols))
flips

array([[1, 0, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 1, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 1, 0, 1],
       [1, 1, 0, ..., 0, 1, 0]])

In [21]:
headss = flips.sum(axis = 1)
prob = (headss == 3).mean()
prob

0.218409

In [22]:
prob = (headss >= 3).mean()
prob

0.856079

Question 3: There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?



In [25]:
n_rows = 10 ** 6
n_cols = 2
probdata = 1/4 

In [26]:
science = np.random.random((n_rows, n_cols))
((science < probdata).sum(axis = 1) == 2).mean()

0.062581

Question 4: Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?



In [28]:
poptart_avg = 3

pop_std = 1.5
n_cols = 4
n_rows = 10 ** 6 
sim_poptarts = np.random.normal(poptart_avg, pop_std, size=(n_rows, n_cols))
sim_poptarts

array([[4.70237675, 2.71043585, 1.4628765 , 3.05017255],
       [2.02148507, 3.45366071, 0.15449546, 3.48931313],
       [5.25833222, 3.52274244, 2.91412983, 3.51669951],
       ...,
       [2.55041615, 3.31540044, 1.96394888, 2.67170162],
       [1.12973881, 1.67527904, 4.82313924, 5.5245309 ],
       [2.213238  , 3.64992165, 1.38355109, 4.10046672]])

In [31]:
prob = (sim_poptarts.sum(axis = 1) <= 16).mean() 
prob

0.908891

Question 5: Compare Heights

    -Men have an average height of 178 cm and standard deviation of 8cm.
    -Women have a mean of 170, sd = 6cm.
    -If a man and woman are chosen at random, P(woman taller than man)?

In [35]:
man_avg = 178 
man_std = 8
lady_avg = 170
lady_std = 6

s_man = np.random.normal(man_avg, man_std, 10**6)
s_man

array([164.24426015, 172.76005838, 175.92371016, ..., 164.75688371,
       172.20464124, 179.12480332])

In [37]:
s_lady = np.random.normal(lady_avg, lady_std, 10**6)
s_lady

array([165.06456457, 174.39829692, 171.10890405, ..., 168.17515335,
       173.34998931, 165.78290084])

In [38]:
prob = (s_lady > s_man).mean()
prob 

0.212744

Question 6: When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?



In [43]:
error_prob = (1/250)
n_cols = 50
n_rows = 10**6
error = 1
success = 0


In [39]:
install = np.random.random((n_rows, n_cols))
install

array([[0.52217802, 0.26588248, 0.16528392, 0.4974502 ],
       [0.09639818, 0.1624841 , 0.11130883, 0.54645469],
       [0.87233147, 0.97926508, 0.35234332, 0.86894559],
       ...,
       [0.18587943, 0.39340662, 0.55860706, 0.44807554],
       [0.0887593 , 0.47643376, 0.23579038, 0.60160307],
       [0.33864992, 0.86857297, 0.37779549, 0.59351142]])

In [48]:
n_cols2 = 100
n_rows2 = 10**6
error = 1
success = 0

In [49]:
install2 = np.random.random((n_rows2, n_cols2))

In [57]:
prob = ((install2 < error_prob).sum(axis = 1) == 0).mean()
prob

0.670069

In [52]:
n_cols3 = 450
n_rows3 = 10**6
error = 1
success = 0

In [56]:
install3 = np.random.random((n_rows3, n_cols3))
install3

array([[0.75443213, 0.7375854 , 0.34056255, ..., 0.41378782, 0.51053245,
        0.45855716],
       [0.73451092, 0.08091764, 0.42752686, ..., 0.38122601, 0.77989924,
        0.36057792],
       [0.55163301, 0.00476358, 0.0346331 , ..., 0.51928152, 0.75278437,
        0.51915464],
       ...,
       [0.01447601, 0.95152888, 0.38112107, ..., 0.88127625, 0.76988763,
        0.74992098],
       [0.78219755, 0.30384462, 0.80409896, ..., 0.3235685 , 0.63728356,
        0.94611258],
       [0.50509539, 0.13809257, 0.26616388, ..., 0.03372767, 0.09103084,
        0.17517096]])

In [58]:
prob = ((install3 < error_prob).sum(axis = 1) == 0).mean()
prob

0.164861

Question 7: There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?


How likely is it that a food truck will show up sometime this week?




In [59]:
n_rows = 10**6
n_cols = 3
truck = 1
no_truck = 0


In [60]:
values = np.random.random((n_rows, n_cols))
prob = 0.7

In [61]:
((values < prob).sum(axis = 1) == 0).mean()

0.027058

In [66]:
n_rows2 = 10**6
n_cols2 = 2
truck2 = 1
no_truck2 = 0
lunch_days = np.random.random((n_rows2, n_cols2))

In [68]:
prob2 = ((lunch_days < prob).sum(axis =1) > 0).mean()
prob2

0.909618

Question 8: If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?



In [ ]:
outcomes = range(0,365)
n_trials = n_cols = 23
n_sims = n_rows = 10**6

In [70]:
classrooms = np.random.choice(outcomes, size=(n_rows, n_cols))
classrooms

array([[5, 6, 6],
       [4, 6, 1],
       [5, 3, 6],
       ...,
       [2, 2, 6],
       [2, 6, 3],
       [4, 2, 1]])

In [72]:
twinsies = [len(np.unique(classrooms[n])) for n in range(0, n_sims-1) if len(np.unique(classrooms[n])) < 23]
twinsies

[2, 3, 3, 3, 3, 2, 2]

In [73]:
prob = len(twinsies) / n_sims
prob

0.875

In [79]:
outcomes = range(0,365)
n_trials = n_cols = 20
n_sims = n_rows = 10**6

In [80]:
twinsies = [len(np.unique(classrooms[n])) for n in range(0, n_sims-1) if len(np.unique(classrooms[n])) < 23]
twinsies

[2,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 1,
 3,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 2,
 2,
 3,
 2,
 3,
 2,
 2,
 2,
 3,
 2,
 3,
 2,
 3,
 2,
 2,
 3,
 3,
 2,
 1,
 2,
 3,
 2,
 2,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 3,
 1,
 2,
 3,
 2,
 3,
 3,
 2,
 3,
 3,
 2,
 3,
 3,
 2,
 1,
 3,
 2,
 2,
 3,
 2,
 3,
 2,
 2,
 3,
 1,
 3,
 2,
 1,
 3,
 3,
 3,
 2,
 2,
 3,
 3,
 2,
 1,
 3,
 2,
 3,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 1,
 2,
 3,
 3,
 2,
 2,
 3,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 2,
 3,
 2,
 2,
 3,
 3,
 3,
 2,
 3,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 2,
 3,
 2,
 3,
 3,
 2,
 3,
 3,
 3,
 2,
 2,
 3,
 2,
 1,
 3,
 2,
 3,
 2,
 3,
 3,
 2,
 3,
 2,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 2,
 3,
 2,
 2,
 3,
 2,
 3,
 2,
 2,
 2,
 3,
 3,
 3,
 1,
 2,
 3,
 3,
 3,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 3,
 3,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 3,
 2,
 2,
 3,
 2,
 3,
 2,
 3,
 2,
 3,
 2,
 2,
 3,


In [81]:
prob = len(twinsies) / n_sims
prob

0.999999

In [82]:
outcomes = range(0,365)
n_trials = n_cols = 40
n_sims = n_rows = 10**6

In [83]:
twinsies = [len(np.unique(classrooms[n])) for n in range(0, n_sims-1) if len(np.unique(classrooms[n])) < 23]
twinsies

[2,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 1,
 3,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 2,
 2,
 3,
 2,
 3,
 2,
 2,
 2,
 3,
 2,
 3,
 2,
 3,
 2,
 2,
 3,
 3,
 2,
 1,
 2,
 3,
 2,
 2,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 3,
 1,
 2,
 3,
 2,
 3,
 3,
 2,
 3,
 3,
 2,
 3,
 3,
 2,
 1,
 3,
 2,
 2,
 3,
 2,
 3,
 2,
 2,
 3,
 1,
 3,
 2,
 1,
 3,
 3,
 3,
 2,
 2,
 3,
 3,
 2,
 1,
 3,
 2,
 3,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 1,
 2,
 3,
 3,
 2,
 2,
 3,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 2,
 3,
 2,
 2,
 3,
 3,
 3,
 2,
 3,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 2,
 3,
 2,
 3,
 3,
 2,
 3,
 3,
 3,
 2,
 2,
 3,
 2,
 1,
 3,
 2,
 3,
 2,
 3,
 3,
 2,
 3,
 2,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 2,
 3,
 2,
 2,
 3,
 2,
 3,
 2,
 2,
 2,
 3,
 3,
 3,
 1,
 2,
 3,
 3,
 3,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 3,
 3,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 3,
 2,
 2,
 3,
 2,
 3,
 2,
 3,
 2,
 3,
 2,
 2,
 3,


In [84]:
prob = len(twinsies) / n_sims
prob

0.999999